cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='shopcart'),
    path('add/<int:variant_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:variant_id>/', views.cart_remove, name='cart_remove'),
]

coupon/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('coupon_apply/', views.coupon_apply, name='coupon_apply'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('orderproduct/', views.order_create, name='orderproduct'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product, Variants
from .cart import Cart
from .forms import CartAddProductForm
from coupon.forms import CouponApplyForm
from coupon.models import Coupon
from django.contrib import messages

@require_POST
def cart_add(request, variant_id):
    cart = Cart(request)
    variant = get_object_or_404(Variants, id=variant_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(variant=variant,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:shopcart')


@require_POST
def cart_remove(request, variant_id):
    cart = Cart(request)
    variant = get_object_or_404(Variants, id=variant_id)
    cart.remove(variant)
    return redirect('cart:shopcart')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/shopcart.html',
                           {
                               'cart': cart,
                            })

cart/templates/cart/shopcart.html
{% extends 'home/index.html' %}

{% block title %}
    سبد خرید
{% endblock %}

{% block content %}
    <!--start suppliers-->
    <div class="container mt-4">
        <div class="table_suppliers mt-4 shadow-sm">
            <table class="table bg-white table-bordered table-responsive_custom">
                <thead>
                <tr class="text-white">
                    <th>نام محصول</th>
                    <th>رنگ</th>
                    <th>سایز</th>
                    <th>قیمت واحد</th>
                    <th>تعداد</th>
                    <th>تخفیف</th>
                    <th>قیمت کل</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with variant=item.variant %}
                    <tr>
                        <td class="table_link">
                            <img style="width: 50px; height: 50px" src="{{ variant.product.image.url }}" alt="{{ variant.product.name }}">
                            <a href="{{ variant.ger_absolute_url }}"><span class="span2">{{ variant.product.name }}</span></a>
                        </td>

                        <td>
                            <strong class="span1">{{ variant.color.name }}</strong>
                        </td>

                        <td>
                            <strong class="span1">{{ variant.size }}</strong>
                        </td>

                        <td>
                        {% if variant.discount_status %}
                        <del class="badge badge-danger">{{ variant.price }}تومان</del><br><strong class="badge badge-success">{{ variant.discount_price }}  تومان</strong>
                        {% else %}
                            <strong class="badge badge-success">{{ variant.price }}تومان</strong>
                        {% endif %}
                        </td>

                        <td>
                            <form action="{% url 'cart:cart_add' variant.id %}" method="post">
                                {% csrf_token %}
                                <div class="pro-qty mb-1">
                                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" max="{{ variant.number }}">
                                    <input type="hidden" name="override" value="{{ item.quantity }}">
                                </div>
                                <button type="submit" class="primary-btn btn">
                                    به روز کردن سبد
                                </button>
                            </form>
                        </td>

                        <td>
                            {% if variant.discount_status %}
                                <strong class="badge badge-success">دارد</strong>
                            {% else %}
                                <strong class="span1 badge badge-danger">ندارد</strong>
                            {% endif %}
                        </td>
                        <td>
                            <strong class="span1">
                                 {{ item.total_price }}    تومان
                            </strong>
                        </td>
                        <td>
                            <form action="{% url 'cart:cart_remove' variant.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" onclick="return confirm('حذف شود؟')">&#10005;</button>
                            </form>
                        </td>
                    </tr>
                    {% endwith %}
                {% endfor %}
                </tbody>
                <tfoot class="text-light">
                    <tr>
                        <th>هزینه ی کل محصولات </th>
                        <th colspan="7" class="bg-light text-info">{{ cart.get_total_price }} تومان</th>
                    </tr>
                    <tr>
                        <th>ارسال</th>
                        <th colspan="7" class="bg-light text-info">{{ post }} تومان</th>
                    </tr>

                    <tr>
                        <th>هزینه ی کل پرداختی</th>
                        <th colspan="7" class="bg-light text-info">
                            {% if cart.coupon %}
                                {% with code=cart.coupon.code discount=cart.coupon.discount %}
                                     کد "{{ code }}"({{ discount }}% تخفیف)
                                {% endwith %}
                            {% endif %}
                                <span>{{ cart.get_total_price_after_discount|floatformat:0 }} تومان</span>
                        </th>
                    </tr>
                </tfoot>
            </table>

                <div class="col-lg-6 mb-5">
                    <div>
                        <div class="m-2">
                            <h5>کد تخفیف</h5>
                            <form action="{% url 'coupons:coupon_apply' %}" method="post">
                                {% csrf_token %}
                                <input type="text" name="code" placeholder="کد تخفیف را وارد نمایید">
                                <button type="submit" class="btn btn-primary btn-sm">ثبت کد تخفیف</button>
                                {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                    (<strong>{{ field.label|escape }}</strong>)
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                    {% endfor %}
                                {% endif %}
                            </form>
                        </div>
                    </div>
                </div>
        {% if cart %}
            <a href="{% url 'order:orderproduct' %}" class="btn btn_custom2 mb-2 shadow-sm"><i class="material-icons">shopping_cart</i>تکمیل خرید</a>
        {% endif %}
        </div>
    </div>


{% endblock %}