cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='shopcart'),
    path('add/<int:variant_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:variant_id>/', views.cart_remove, name='cart_remove'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact_us, name='contact'),
    path('articles/', views.articles, name='articles'),
    path('details_articles/<int:id>', views.details_articles, name='details_articles'),
    path('details/<int:id>/<str:slug>/', views.details, name='details'),
    path('katoni/', views.katoni, name='katoni'),
    path('katoni/brand/<str:brand_slug>', views.katoni, name='katoni_brand'),
    path('katoni/category/<str:category_slug>', views.katoni, name='katoni_category'),
    path('tags/<str:tag_slug>', views.product_tag, name='product_tag'),
    path('feminine/', views.feminine, name='feminine'),
    path('both/', views.both, name='both'),
    path('for_men/', views.for_men, name='for_men'),
    path('discounts/', views.discounts, name='discounts'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('orderproduct/', views.order_create, name='orderproduct'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # path('', views.index, name='index'),
    path('addcomment/<int:id>/', views.addcomment, name='addcomment'),
]

home/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Setting(models.Model):
    class Meta:
        verbose_name = 'مشخصات'
        verbose_name_plural = 'مشخصات'

    title = models.CharField('عنوان', max_length=60)
    phone = models.CharField('تلفن', max_length=60)
    address = models.CharField('آدرس', max_length=60)
    description = models.TextField('توضیحات')
    email = models.CharField('ایمیل', max_length=60)
    telegram = models.CharField('تلگرام', max_length=60)
    instagram = models.CharField('اینستاگرام', max_length=60)
    icon = models.ImageField('لوگو', blank=True, upload_to='katoni_images/setting')
    created = models.DateTimeField('ایجاد', auto_now_add=True)
    updated = models.DateTimeField('به روز رسانی', auto_now=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقاله ها'

    title = models.CharField('عنوان', max_length=100)
    cover = models.ImageField('کاور', upload_to='katoni_images/articles')
    text = RichTextField('متن')

    created = models.DateTimeField('انتشار', auto_now_add=True)
    updated = models.DateTimeField('به روز رسانی', auto_now=True)

    def __str__(self):
        return self.title

class Contact(models.Model):
    class Meta:
        verbose_name = 'پیام'
        verbose_name_plural = 'پیام ها'
    
    first_name = models.CharField('نام', max_length=128)
    last_name = models.CharField('نام خانوادگی', max_length=128)
    email = models.EmailField('ایمیل')
    message = models.TextField('پیام')

    created = models.DateTimeField('انتشار', auto_now_add=True)
    updated = models.DateTimeField('به روز رسانی', auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

home/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

product/forms.py
from django import forms
from .models import Comment, Product


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

home/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse

from product.models import Category, Product, Comment, Images, Variants, Brand, IpAddress, Color, Slider
from user.models import User
from .models import Setting, Article, Contact
from .forms import ContactForm
from django.core.paginator import Paginator, EmptyPage

# search_form
from product.filter import ProductFilter, VariantFilter
# Create your views here.


def home(request):
    context = {
        'category': Category.objects.all(),
        'product': Product.objects.all(),
        'brand': Brand.objects.all(),
        'news': Product.objects.all().order_by('-id')[:5],
        'discount': Product.objects.filter(discount_status=True),
        'articles': Article.objects.all(),
        'sliders': Slider.objects.all().order_by('-id')[:4]
    }
    return render(request, 'home/home.html', context)


def about(request):
    try: 
        setting = get_object_or_404(Setting, pk=1)
        context = {
            'setting': setting
        }
        return render(request, 'home/about.html', context)
    except:
        return redirect('home:home')

def contact_us(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return redirect('home:contact')
    else:
        contact_form = ContactForm()
    return render(request, 'home/contact.html', {
        'contact_form': contact_form
    })


def articles(request):
    context = {
        'articles': Article.objects.all(),
    }
    return render(request, 'home/articles.html', context)


def details_articles(request, id):
    context = {
        'articles': get_object_or_404(Article, pk=id)
    }
    return render(request, 'home/details_articles.html', context)


def details(request, id, slug):
    query = request.GET.get('q')
    product = get_object_or_404(Product, id=id, slug=slug)

    for ip_address in IpAddress.objects.all():
        if ip_address not in product.hits.all():
            product.hits.add(ip_address)

    context = {
        'product': product,
        'product_related': Product.objects.filter(brand__name=product.brand.name).exclude(id=id)[:4],
        'images': Images.objects.filter(product_id=id),
        'comments': Comment.objects.filter(product_id=id, active=True).order_by('-id'),
    }
    
    if product.variant != 'None':
        if request.method == 'POST':
            variant_id = request.POST.get('variantid')
            variant = Variants.objects.get(id=variant_id)
            colors = Variants.objects.filter(product_id=id, size_id=variant.size_id)
            sizes = Variants.objects.filter(product_id=id).values('size_id', 'size__name').distinct()
            # query += variant.title + ' size:' + str(variant.size) + ' color:' + variant.color

        else:
            variants = Variants.objects.filter(product_id=id)
            colors = Variants.objects.filter(product_id=id, size_id=variants[0].size_id)
            sizes = Variants.objects.filter(product_id=id).values('size_id', 'size__name').distinct()
            variant = Variants.objects.get(id=variants[0].id)
        context.update({
            'sizes': sizes,
            'colors': colors,
            'variant': variant,
            'query': query
        })
    return render(request, 'home/product.html', context)


def ajaxcolor(request):
    data = {}
    if request.POST.get('action') == 'post':
        size_id = request.POST.get('size')
        productid = request.POST.get('productid')
        colors = Variants.objects.filter(product_id=productid, size_id=size_id)
        context = {
            'size_id': size_id,
            'productid': productid,
            'colors': colors,
        }
        data = {'rendered_table': render_to_string('home/color_list.html', context, request=request)}
        return JsonResponse(data)
    return JsonResponse(data)


def katoni(request, brand_slug=None, category_slug=None):
    category = None
    categories = Category.objects.all()
    brand = None
    brands = Brand.objects.all()
    katonis = Product.objects.all().order_by('-id').order_by('status')

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        katonis = katonis.filter(category=category)
    elif brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        katonis = katonis.filter(brand=brand)



    search_brand = request.GET.get('search_brand')
    search = request.GET.get('search')
    if search_brand:
        katonis = Product.objects.filter(Q(brand__name__in=request.GET.getlist('search_brand'))
                                           | Q(status=True)
                                           | Q(name__icontains=search)).distinct().order_by('-id').order_by('status')

    product_filter = ProductFilter(request.GET, queryset=katonis)
    variant_filter = VariantFilter(request.GET, queryset=Variants.objects.all())
    katonis = product_filter.qs
    pagination = Paginator(katonis, 20)
    page_number = request.GET.get('page')
    pages = pagination.get_page(page_number)

    context = {
        'category': category,
        'katonis': katonis,
        'pages': pages,
        'pagination': pagination,
        'product_filter': product_filter,
        'variant_filter': variant_filter,
        'search_brand': search_brand,
        'brands': Brand.objects.all(),
        'colors': Color.objects.all(),
        'pro_count': Product.objects.all().count(),
    }
    return render(request, 'home/katonis.html', context)


def for_men(request):
    category = Category.objects.all()
    search_bar = request.GET.get('search_bar')
    if search_bar:
        for_men = Product.objects.filter(Q(name__icontains=search_bar)
                                         | Q(brand__name__icontains=search_bar)
                                         | Q(orderproduct__variant__size__name=search_bar)
                                         | Q(orderproduct__variant__color__name=search_bar)
                                         | Q(status=True)
                                         & Q(man=True)).distinct().order_by('-id').order_by('status')
    else:
        for_men = Product.objects.filter(man=True).order_by('-id').order_by('status')
    product_filter = ProductFilter(request.GET, queryset=for_men)

    variant_filter = VariantFilter(request.GET, queryset=Variants.objects.all())

    for_men = product_filter.qs
    pagination = Paginator(for_men, 20)
    page_number = request.GET.get('page')
    pages = pagination.get_page(page_number)
    context = {
        'category': category,
        'pages': pages,
        'pagination': pagination,
        'product_filter': product_filter,
        'variant_filter': variant_filter,
        'search_bar': search_bar,
        'brands': Brand.objects.all(),
        'colors': Color.objects.all(),
        'pro_count': Product.objects.filter(man=True).count(),
    }
    return render(request, 'home/for_men.html', context)


def feminine(request):
    category = Category.objects.all()
    search_bar = request.GET.get('search_bar')
    if search_bar:
        feminine = Product.objects.filter(Q(name__icontains=search_bar)
                                          | Q(brand__name__icontains=search_bar)
                                          | Q(orderproduct__variant__size__name=search_bar)
                                          | Q(orderproduct__variant__color__name=search_bar)
                                          | Q(status=True)
                                          & Q(women=True)).distinct().order_by('-id').order_by('status')
    else:
        feminine = Product.objects.filter(women=True).order_by('-id').order_by('status')
    product_filter = ProductFilter(request.GET, queryset=feminine)
    variant_filter = VariantFilter(request.GET, queryset=Variants.objects.all())

    feminine = product_filter.qs
    pagination = Paginator(feminine, 20)
    page_number = request.GET.get('page')
    pages = pagination.get_page(page_number)
    context = {
        'category': category,
        'pages': pages,
        'pagination': pagination,
        'product_filter': product_filter,
        'variant_filter': variant_filter,
        'search_bar': search_bar,
        'brands': Brand.objects.all(),
        'colors': Color.objects.all(),
        'pro_count': Product.objects.filter(women=True).count(),
    }
    return render(request, 'home/feminine.html', context)


def both(request):
    category = Category.objects.all()
    search_bar = request.GET.get('search_bar')
    if search_bar:
        both = Product.objects.filter(Q(name__icontains=search_bar)
                                          | Q(brand__name__icontains=search_bar)
                                          | Q(orderproduct__variant__size__name=search_bar)
                                          | Q(orderproduct__variant__color__name=search_bar)
                                          | Q(status=True)
                                          & Q(women=True)
                                          & Q(man=True)).distinct().order_by('-id').order_by('status')
    else:
        both= Product.objects.filter(women=True, man=True).order_by('-id').order_by('status')
    product_filter = ProductFilter(request.GET, queryset=both)
    variant_filter = VariantFilter(request.GET, queryset=Variants.objects.all())

    both = product_filter.qs
    pagination = Paginator(both, 20)
    page_number = request.GET.get('page')
    pages = pagination.get_page(page_number)
    context = {
        'category': category,
        'pages': pages,
        'pagination': pagination,
        'product_filter': product_filter,
        'variant_filter': variant_filter,

product/views.py
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from product.forms import CommentForm
from product.models import Comment


# def index(request):
#
#     return HttpResponse("product page")


def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = Comment()
            # data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.product_id = id
            current_user = request.user
            data.user_id = current_user.id
            data.save()
            messages.success(request, 'نظر شما با موفقیت ثبت شد. ممنون از ارسال نظر شما...')
            return HttpResponseRedirect(url)

    return HttpResponseRedirect(url)

home/templates/home/about.html
{% extends 'home/index.html' %}

{% block title %}
    درباره ی ما
{% endblock %}


{% block content %}
<div class="row p-3">
        <div class="col-9 item-details">
            <div class="row px-3">
                <div class="col-4">
                    <small class="text-muted">
                        <p>عنوان:</p>
                    </small>
                </div>
                <div class="col-8">
                   <p>{{ setting.title }}</p>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <p>تلفن:</p>
                    </small>
                </div>
                <div class="col-8">
                    <p>{{ setting.phone }}</p>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <p>آدرس:</p>
                    </small>
                </div>
                <div class="col-8">
                    <p>{{ setting.address }}</p>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <p>ایمیل:</p>
                    </small>
                </div>
                <div class="col-4">
                    <p>{{ setting.email }}</p>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <p>تلگرام:</p>
                    </small>
                </div>
                <div class="col-8">
                    <p>{{ setting.telegram }}</p>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <p>اینستاگرام:</p>
                    </small>
                </div>
                <div class="col-4">
                    <p>{{ setting.instagram }}</p>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-9">
                    <small class="text-muted">
                        <p>توضیحات:</p>
                    </small>
                </div>
                <div class="col-9">
                    <p>{{ setting.description }}</p>
                </div>
            </div>
        </div>
</div>
{% endblock %}

home/templates/home/articles.html
{% extends 'home/index.html' %}
{% load static %}



{% block content %}
    <div class="container-fluid ads mt-4 mb-4">
        <div class="row">
            {% for article in articles %}
                <div class="col-md-3 col-6 serv text-center">
                    <a href="{% url 'home:details_articles' id=article.id %}"><img src="{{ article.cover.url }}" style="height: 250px;" class="w-100 d-block rounded" alt=""></a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block extra_headers %}{% endblock %}


    <link rel="stylesheet" href="{% static 'home/New folder/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/base.css' %}?{% now "U" %}">

    
    
    
    
    <script src="{% static 'home/js/all.min.js' %}"></script>

{#     slides package#}
    <link rel="stylesheet" href="{% static 'home/css/uikit.min.css' %}">
    <script src="{% static 'home/js/uikit.min.js' %}"></script>
    <script src="{% static 'home/js/uikit-icons.min.js' %}"></script>

    <title>{% block title %}Shop_Katoni{% endblock %}</title>



    {% block extra_css %}{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

</head>
<body>
    
    <header>

        <div class="number">
            <p>
                شماره ی ارتباطی: 09184301291
            </p>
        </div>

        
        <div class="user float-left">
        {% if user.is_authenticated %}
                <div class="btn-group dropleft">
                    <button type="button" class="btn btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.first_name }}
                        <i class="fas fa-user"></i>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        {% if user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'registration:adminpnl' %}">
                                پنل مدیریت
                            </a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'registration:profile' %}">
                            پروفایل
                        </a>
                        <a class="dropdown-item" href="{% url 'registration:orders' %}">
                            سفارشات من
                        </a>
                        <a class="dropdown-item" href="{% url 'registration:logout' %}">
                            خروج
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="btn-group dropleft">
                    <button type="button" class="btn btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i>
                        حساب کاربری
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'registration:login' %}">
                            ورود به پنل کاربری
                        </a>
                        <a class="dropdown-item" href="{% url 'registration:signup' %}">
                            ثبت نام
                        </a>
                    </div>
                </div>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'order:shopcart' %}" class="btn btn-outline-dark" type="button">
                 <span class="badge badge-danger">
                 {% load myapptags %}
                 {% shopcart_count user.id as count %}
                 {{ count }}
                </span>
                سبد خرید
                <i class="fas fa-shopping-cart"></i>
                </a>
            {% else %}
                <a href="{% url 'registration:login' %}" class="btn btn-outline-dark" type="button">
                <i class="fas fa-user"></i>
                ورود
                </a>
            {% endif %}


        </div>

        {% block search_bar %}{% endblock %}

        <div class="navbar_1">
            <nav class="navbar navbar-expand-lg navbar-light bg-gradient-white">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home:home' %}">
                                <i class="fas fa-home"></i>
                                خانه 
                                <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'home:katoni' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                کتونی ها
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'home:for_men' %}">مردانه</a>
                                <a class="dropdown-item" href="{% url 'home:feminine' %}">زنانه</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">حراجی ها</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:about' %}">درباره ی ما</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'home:katoni' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                مقالات
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% for article in articles %}
                                    <a class="dropdown-item" href="{% url 'home:articles' id=article.id %}">{{ article.title }}</a>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                    
                </div>
              </nav>
        </div>
    </header>

    <div class="clear"></div>
    {% block slider %}

    {% endblock %}
    

    <div class="clear"></div>
    
    {% block items %}

    {% endblock %}

    <div class="clear"></div>

    {% block takhfif %}

    {% endblock %}
    

    <div class="clear"></div>
    
    {% block randome_item %}

    {% endblock %}

    {% block content %}

    {% endblock %}    
      
    
    <div class="clear"></div>
    
    {% block item_slider %}

    {% endblock %}

    <div class="clear"></div>

    {% block ads %}

    {% endblock %}

    <div class="clear"></div>
    
    {% block brands %}

    {% endblock %}

    {% block comment %}

    {% endblock %}

    <div class="clear"></div>

    
    <footer>

        <div class="row items">
            <div class="col-md-4 col-6 serv text-center item">
                <img src="/static/home/img/delivery-truck.png" alt="">
                <p>
                    ارسال سریع مرسولات
                </p>
                <p class="text">
                    سفارش های پستی در تهران 24 ساعت پس از ارسال و شهرهای دیگه تا 72 ساعت به دست گیرنده میرسن
                </p>
            </div>

            <div class="item">
                <img src="/static/home/img/credit-card.png" alt="">
                <p>
                    پرداخت امن و آنلاین
                </p>
                <p class="text">
                    درگاه های پرداخت سرویس دهنده های معتبر برای پرداختی آسوده و امن
                </p>
            </div>

            <div class="col-md-4 col-6 serv text-center item">

                <img src="/static/home/img/check.png" alt="">
                <p>
                    بسته بندی اصلی محصول
                </p>
                <p class="text">
                    تمام کتونی ها با کارتن و محتویات اصلی ارسال می شوند
                </p>
            </div>

        </div>

        <hr class="danger">

        <div class="clear"></div>

      <div class="float-right">
        <p>راهنمای مشتریان</p>
        <ul>
          <a href="{% url 'home:size' %}"><li>اندازه گیری سایز</li></a>
          <a href="{% url 'home:safe' %}"><li>درگاه امن</li></a>
        </ul>
      </div>
      
      <div class="contact mx-auto">
        <p> راه های ارتباطی با فروشگاه</p>
        <ul>
            <li><a target="_blank" href="https://www.instagram.com/shop_katoni_1/"><img src="/static/home/img/instagram%20(2).png" alt=""></a></li>
            <li><a href=""><img src="/static/home/img/telegram.png" alt=""></a></li>
        </ul>
      </div>

    </footer>


    <script src="{% static 'home/js/base.js' %}"></script>

    
    <script src="{% static 'home/jS/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'home/New folder/jS/bootstrap.bundle.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</body>
</html>

home/templates/home/color_list.html
<form id="appendHere" method="POST" action="?q=selectvariant" id="post-color">
    <input type="hidden" name="size" id="size" value="{{ size_id }}">
    {% csrf_token %}
    {% for color in colors %}
        <li class="list-inline-item box_check1">
            <input type="radio" style="background-color: {{ color.color.code }};" {% if variant.id == color.id %} checked {% endif %}
                   name="variantid" id="{{ color.color.id }}" value="{{ color.id }}" onchange="this.form.submit();">
            <label class="check1" style="background-color: {{ color.color.code }}" for="{{ color.color.id }}"><span>{{ color.color.name }}</span></label>
        </li>
    {% endfor %}
</form>

home/templates/home/details_articles.html
{% extends 'home/index.html' %}
{% load static %}


{% block title %}
    {{ articles.title }}
{% endblock %}



{% block content %}
    <div class="container-fluid m-3">
        <h4>{{ articles.title }}</h4>
        <img src="{{ articles.cover.url }}" alt="">
        <br><br>
        <p>{{ articles.text }}</p>
    </div>
{% endblock %}

home/templates/home/size.html
{% extends 'home/base.html' %}
{% load static %}


{% block title %}
    اندازه گیری سایز
{% endblock %}


{% block content %}

{% endblock %}