cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='shopcart'),
    path('add/<int:variant_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:variant_id>/', views.cart_remove, name='cart_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('orderproduct/', views.order_create, name='orderproduct'),
]

order/models.py
from datetime import datetime
from decimal import Decimal

from django.core.validators import MinValueValidator, MaxValueValidator

from coupon.models import Coupon
from user.models import User
from django.db import models
from extensions.utils import jalali_converter

# Create your models here.
from product.models import Product, Variants, Discount


class Order(models.Model):
    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش'

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='کاربر')
    code = models.CharField('کد خرید', max_length=5, editable=False)
    first_name = models.CharField('نام', max_length=150)
    last_name = models.CharField('نام خانوادگی', max_length=150)
    phone = models.CharField('تلفن', blank=True, max_length=11)
    address = models.CharField('آدرس', max_length=250)
    city = models.CharField('شهر', max_length=75)
    postal_code = models.CharField('کد پستی', max_length=11)
    paid = models.BooleanField('پرداخت شد؟', default=False)
    STATUS_CHOICES = (
        ('در حال بررسی', 'در حال بررسی'),
        ('ارسال شد', 'ارسال شد'),
        ('کنسل شد', 'کنسل شد'),
    )
    status = models.CharField('وضعیت', choices=STATUS_CHOICES, max_length=50, default='در حال بررسی')

    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, related_name='orders', null=True, blank=True, verbose_name='کد تخفیف')
    discount = models.IntegerField('تخفیف', default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    created = models.DateTimeField('ایجاد', auto_now_add=True)
    updated = models.DateTimeField('به روز رسانی', auto_now=True)

    def __str__(self):
        return self.first_name

    def jcreated(self):
        return jalali_converter(self.created)
    jcreated.short_description = 'تاریخ سفارش'

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal(100))

    get_total_cost.short_description = 'مبلغ کل'


class OrderProduct(models.Model):
    class Meta:
        verbose_name = 'سفارش محصول'
        verbose_name_plural = 'سفارش محصول'

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name='سفارش')
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='مشخصه')  # relation with variant
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, related_name='product_orderitem', null=True, verbose_name='محصول')
    quantity = models.IntegerField('تعداد')
    price = models.IntegerField('قیمت')
    total_price = models.PositiveIntegerField('قیمت کامل')

    created = models.DateTimeField('ایجاد', auto_now_add=True)
    updated = models.DateTimeField('به روز رسانی', auto_now=True)

    def __str__(self):
        return self.variant.product.name

    def get_cost(self):
        return self.quantity * self.price

order/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'postal_code', 'address', 'city']

order/views.py
from smtplib import SMTPAuthenticationError

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage, send_mail

# Create your views here.
from django.urls import reverse
from django.utils.crypto import get_random_string

from cart.cart import Cart
from order.forms import OrderForm
from order.models import OrderProduct, Order
from product.models import Category, Product, Variants


# @login_required(login_url='account:account_login')
# def orderproduct(request):
#     category = Category.objects.all()
#     current_user = request.user
#     shopcart = ShopCart.objects.filter(user_id=request.user.id)
#     profile = User.objects.get(pk=request.user.pk)
#
#     post = 40000
#     total = 0
#     for rs in shopcart:
#         if rs.product.dis_price:
#             total += rs.product.dis_price * rs.quantity
#         else:
#             total += rs.product.price * rs.quantity
#
#     if request.method == 'POST':
#         form = OrderForm(request.POST)
#         if form.is_valid():
#             data = Order()
#             data.first_name = form.cleaned_data['first_name']
#             data.last_name = form.cleaned_data['last_name']
#             data.city = form.cleaned_data['city']
#             data.address = form.cleaned_data['address']
#             data.phone = form.cleaned_data['phone_number']
#             data.postal_code = form.cleaned_data['postal_code']
#             data.user_id = current_user.id
#             data.total = total
#             ordercode = get_random_string(5).upper()
#             data.code = ordercode
#             data.save()
#
#             shopcart = ShopCart.objects.filter(user_id=request.user.id)
#             for item in shopcart:
#                 detail = OrderProduct()
#                 detail.order_id = data.id
#                 detail.product_id = item.product_id
#                 detail.user_id = current_user.id
#                 detail.quantity = item.quantity
#                 if item.product.dis_price:
#                     detail.price = item.product.dis_price
#                 else:
#                     detail.price = item.product.price
#                 detail.variant_id = item.variant_id
#                 detail.amount = item.amount
#                 detail.save()
#
#                 # کم کردن تعداد محصول
#                 variant = Variants.objects.get(id=item.variant_id)
#                 variant.number -= item.quantity
#                 variant.save()
#
#             ShopCart.objects.filter(user_id=request.user.id).delete()
#             request.session['cart_items'] = 0
#             messages.success(request, 'خرید شما کامل شده. ممنون از اعتماد شما')
#             context = {
#                 'category': category,
#                 'ordercode': ordercode,
#                 'shopcart': shopcart,
#                 'current_user': current_user,
#                 'total': total,
#             }
#             try:
#                 # تنظیمات ارسال فاکتور خرید با ایمیل
#                 message = get_template('order/mail_order.html').render(context)
#                 msg = EmailMessage(
#                     'فاکتور خرید',
#                     message,
#                     'shopkatoni99@gmail.com',
#                     [request.user.email],
#                 )
#                 msg.content_subtype = 'html'
#                 msg.send()
#                 print('mail send')
#                 return render(request, 'order/ordercomplate.html', context)
#             except SMTPAuthenticationError:
#                 messages.error(request, 'متاسفانه مشکلی در سیستم وجود دارد و ایمیل برای شما ارسال نشده است اما خرید شما تکمیل گردید و نگرانی از این بابت نداشته باشید.')
#                 return render(request, 'order/ordercomplate.html', context)
#         else:
#             messages.error(request, form.errors)
#             return HttpResponseRedirect(reverse('order:orderproduct'))
#
#     form = OrderForm()
#     context = {
#         'category': category,
#         'shopcart': shopcart,
#         'total': total,
#         'profile': profile,
#         'total_post': total + post
#     }
#     return render(request, 'order/orderproduct.html', context)


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.user = request.user
            code = get_random_string(8)
            order.code = code
            order.save()
            for item in cart:
                variant = item['variant']
                OrderProduct.objects.create(
                    order=order,
                    product=variant.product,
                    variant=item['variant'],
                    price=item['price'],
                    quantity=item['quantity'],
                    total_price=item['total_price']
                )
                variant = Variants.objects.get(title=item['variant'])
                variant.number -= item['quantity']
                variant.save()
            # clear the cart
            cart.clear()
            # clear the coupon code
            request.session['coupon_id'] = None
            # set order in session
            request.session['order_id'] = order.id
            try:    
                context = {
                    'order': Order.objects.get(code=code)
                }
                # تنظیمات ارسال فاکتور خرید با ایمیل
                message_cos = render_to_string('order/mail_order.html', context)
                msg = EmailMessage(
                    'فاکتور خرید',
                    message_cos,
                    'shopkatoni@shopkatoni.ir',
                    [request.user.email],
                )
                msg.content_subtype = 'html'
                msg.send()
                # تنظیمات ارسال فاکتور خرید با ایمیل
                subject = 'ثبت سفارش'
                message_admin = f'''با سلام و خسته نباشید {request.user.username}
                یک سفارش با موفقیت ثبت شد.'''
                send_mail(subject, message_admin, 'shopkatoni@shopkatoni.ir', ['moeinkhorami99@gmail.com'], fail_silently=False)
                messages.success(request, 'خرید با موفقیت ثبت شد.')
                return redirect(reverse('home:home'))
            except SMTPAuthenticationError:
                messages.error(request, 'خرید با موفقیت ثبت شد.')
                return redirect(reverse('home:home'))

    else:
        form = OrderForm()
    return render(request, 'order/orderproduct.html', {
        'form': form,
        'cart': cart
    })

order/templates/order/mail_order.html
<!DOCTYPE html>
<head>
    <style>

        body {
	        direction: rtl;
        }
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: right;
          padding: 8px;
        }
    </style>
</head>
<html>
    <body style="direction: rtl; text-align: right">
        <h1>فروشگاه شاپ کتونی</h1>
        <h3>
            راه ارتباطی: 09184301291 واتساپ
            <a target="_blank" href="https://www.instagram.com/shop_katoni_1/">پیچ شاپ کتونی</a>
        </h3>
        <h2>فاکتور خرید</h2>
        <p>{{ order.first_name }} {{ order.last_name }} عزیز</p>

        <table style="border-collapse: collapse; width: 100%">
            <tr style="background-color: #fff729">
                <th style="text-align: right">شماره</th>
                <th style="text-align: right">محصول</th>
                <th style="text-align: right">رنگ</th>
                <th style="text-align: right">سایز</th>
                <th style="text-align: right">فیمت واحد</th>
                <th style="text-align: right">تعداد</th>
                <th style="text-align: right">قیمت</th>
                <th style="text-align: right">تخفیف</th>
            </tr>
            {% for pro in order.items.all %}
            <tr style="background-color: #72706f">
                <td style="text-align: right">
                    {{ forloop.counter }}
                </td>
                <td style="text-align: right">
                    {{ pro.product.name }}
                </td>
                <td style="text-align: right">
                    {{ pro.variant.color }}
                </td>
                <td style="text-align: right">
                    {{ pro.variant.size }}
                </td>
                <td style="text-align: right">
                    {% if pro.variant.discount_status %}
                        <del class="badge badge-danger">{{ pro.variant.price }}تومان</del><br><strong class="badge badge-success">{{ pro.variant.discount_price }}  تومان</strong>
                    {% else %}
                        <strong class="badge badge-success">{{ pro.variant.price }}تومان</strong>
                    {% endif %}
                </td>
                <td style="text-align: right">
                    {{ pro.quantity }}
                </td>
                <td style="text-align: right">
                    {{ pro.total_price }}
                </td>
                <td style="text-align: right">
                    {% if pro.variant.discount_status %}
                        <strong class="badge badge-success">دارد</strong>
                    {% else %}
                        <strong class="span1 badge badge-danger">ندارد</strong>
                    {% endif %}
                </td>
            </tr>   
            {% endfor %}
            <tr style="background-color: #72706f">
                <th style="text-align: right">کد خرید</th>
                <td style="text-align: right">{{ order.code }}</td>
            </tr>
            <tr style="background-color: #72706f">
                <th style="text-align: right">مبلغ خرید</th>
                <td style="text-align: right"> {{ order.get_total_cost }}تومان</td>
            </tr>
        </table>
        <h4>
از خرید شما بسیار ممنونیم.
        </h4>
    </body>
</html>

order/templates/order/ordercomplate.html
{% extends 'home/index.html' %}

{% block title %}
    تکمیل خرید
{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="col-7 item-details pr-5">
        <div class="row px-3">
            <div class="col-9">
                 <p>{{ user.first_name }} {{ user.last_name }} عزیز</p>
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-9">
                 <p>خرید شما تکمیل شد</p>
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    <p>کد خرید شما:</p>
                </small>
            </div>
            <div class="col-9">
                <p>{{ ordercode }}</p>
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-9">
                 <p>خیلی ممنون از خرید شما</p>
            </div>
    </div>
</div>
{% endblock %}

order/templates/order/orderproduct.html
{% extends 'home/index.html' %}

{% block title %}
    سفارش محصول
{% endblock %}


{% block content %}
    <div class="warining alert-warning text-center">
        <p class="text-danger">** توجه داشته باشید که حتما اطلاعات دقیق را وارد نمایید تا در ارسال محصول مشکلی نباشد. **</p>
    </div>
    <form action="" method="post">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% csrf_token %}
    <div class="container-fluid">
        <div class="col-lg-6 float-right">
            <div>
                <h4>فرم خرید:</h4>
            </div>
            <hr>
            <p><label for="id_first_name">نام:</label></p>
            <input type="text" name="first_name" class="form-control"
                   maxlength="10" required id="id_first_name">
            <br>
            <p><label for="id_last_name">نام خانوادگی:</label></p>
            <input type="text" name="last_name" class="form-control"
                   maxlength="10" required id="id_last_name">
            <br>
            <p><label for="id_city">شهر:</label></p>
            <input type="text" name="city" class="form-control"
                   maxlength="50" required id="id_city">
            <br>
            <p><label for="id_address">آدرس:</label></p>
            <input type="text" name="address" class="form-control"
                   maxlength="250" required id="id_address">
            <br>
            <p><label for="id_postal_code">کد پستی:</label></p>
            <input type="text" name="postal_code" class="form-control"
                   maxlength="20" required id="id_postal_code">
            <br>
            <p><label for="id_phone">تلفن:</label></p>
            <input type="text" name="phone" class="form-control"
                    maxlength="11" required id="id_phone">
            <br>

        </div>
        <div class="col-lg-6 float-left">
            <div>
                <h4>فرم پرداخت:</h4>
            </div>
            <hr>
            <p><label for="id_first_name">مبلغ کل:</label></p>
            <input type="text" name="total" value="{{ cart.get_total_price_after_discount|floatformat:0 }}" class="form-control"
                   maxlength="10" required id="id_total" disabled>
            <br>
            <p><label for="id_card_number">شماره کارت:</label></p>
            <input type="text" name="card_number" value="" class="form-control"
                   maxlength="20" required id="id_card_number">
            <br>
            <p><label for="id_CVV">CVV:</label></p>
            <input type="text" name="CVV" value="" class="form-control"
                   maxlength="10" required id="id_CVV">
            <br>
            <p><label for="id_date_card">تاریخ کارت:</label></p>
            <input type="text" name="date_card" value="" class="form-control"
                   maxlength="10" required id="id_date_card" placeholder="ماه/سال">
            <br>
            <p><label for="id_security_card">رمز دوم:</label></p>
            <input type="text" name="security_card" value="" class="form-control"
                   maxlength="20" required id="id_security_card">
            <br>
            <div>
            <button class="btn btn_custom2 mb-2 shadow-sm"><i class="material-icons">shopping_cart</i>تکمیل خرید</button>
            </div>
        </div>
    </div>

        <br>
    </form>

    <div class="container table_suppliers mt-4">
            <table class="table bg-white table-bordered table-responsive_custom">
                <thead>
                <tr class="text-white">
                    <th>نام محصول</th>
                    <th>رنگ</th>
                    <th>سایز</th>
                    <th>قیمت واحد</th>
                    <th>تعداد</th>
                    <th>تخفیف</th>
                    <th>قیمت کل</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with variant=item.variant %}
                    <tr>
                        <td class="table_link">
                            <img style="width: 50px; height: 50px" src="{{ variant.product.image.url }}" alt="{{ variant.product.name }}">
                            <a href="{{ variant.product.get_absolute_url }}"><span class="span2">{{ variant.product.name }}</span></a>
                        </td>

                        <td>
                            <strong class="span1">{{ variant.color.name }}</strong>
                        </td>

                        <td>
                            <strong class="span1">{{ variant.size }}</strong>
                        </td>

                        <td>
                        {% if variant.discount_status %}
                        <del class="badge badge-danger">{{ variant.price }}تومان</del><br><strong class="badge badge-success">{{ variant.discount_price }}  تومان</strong>
                        {% else %}
                            <strong class="badge badge-success">{{ variant.price }}تومان</strong>
                        {% endif %}
                        </td>

                        <td>
                            <strong class="span1">{{ item.quantity }}</strong>
                        </td>

                        <td>
                            {% if variant.discount_status %}
                                <strong class="badge badge-success">دارد</strong>
                            {% else %}
                                <strong class="span1 badge badge-danger">ندارد</strong>
                            {% endif %}
                        </td>
                        <td>
                            <strong class="span1">
                                 {{ item.total_price }}    تومان
                            </strong>
                        </td>
                        <td>
                            <form action="{% url 'cart:cart_remove' variant.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit"  onclick="return confirm('حذف شود؟')">&#10005;</button>
                            </form>
                        </td>
                    </tr>
                    {% endwith %}
                {% endfor %}
            </table>
    </div>
{% endblock %}